services:
  - type: web
    name: invoice-app
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn invoice_project.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: invoice-db
          property: connectionString

databases:
  - name: invoice-db
    databaseName: invoice_db
    user: invoice_user
    plan: free