# Generated by Django 5.0.2 on 2025-08-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(to='quotations.item'),
        ),
    ]
