# Generated by Django 5.0.2 on 2025-08-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Invoice Number'),
        ),
    ]
