# Generated by Django 5.0.2 on 2025-08-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Number'),
        ),
    ]
