# Generated by Django 5.0.2 on 2025-08-17 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=7.5, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('items', models.ManyToManyField(to='quotations.item')),
            ],
        ),
    ]
