# Generated by Django 5.0.2 on 2025-08-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='lead_time_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
