# Generated by Django 5.0.2 on 2025-08-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_quotation_lead_time_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='lead_time_days',
        ),
        migrations.AddField(
            model_name='quotation',
            name='lead_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
