# Generated by Django 5.0.2 on 2025-08-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_remove_quotation_lead_time_days_quotation_lead_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='rfq_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Request for Quotation Number'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vessel Name'),
        ),
    ]
