# Generated by Django 5.0.2 on 2025-08-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_quotation_rfq_number_quotation_vessel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='lead_time',
        ),
        migrations.AddField(
            model_name='item',
            name='lead_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lead Time'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Notes'),
        ),
    ]
