# Generated by Django 5.0.2 on 2025-08-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_remove_quotation_lead_time_item_lead_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Quotation Number'),
        ),
    ]
