# Generated by Django 5.0.2 on 2025-08-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_quotation_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quotation Number'),
        ),
    ]
