# Generated by Django 5.1.7 on 2025-09-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_remove_unique_quotation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('EA', 'Each'), ('PCS', 'Pieces'), ('KG', 'Kilograms'), ('LTR', 'Liters'), ('M', 'Meters'), ('BOX', 'Box'), ('SET', 'Set'), ('UNIT', 'Unit')], default='EA', max_length=10, verbose_name='Unit'),
        ),
    ]
